import { CategoryAudioI, CategoryImagesI } from './models';

export const MATH_RANDOM = 0.5;
export const PLAYING_AUDIO_TIMEOUT = 1000;
export const ENDGAME_BLOCK_TIMEOUT = 5000;
export const STAR_BLOCK_LENGTH = 20;
export const ONE_HUNDRED = 100;

export const russianWord = new Map([
  ['cat', 'кот'],
  ['bird', 'птица'],
  ['chick', 'цыпленок'],
  ['chicken', 'курица'],
  ['dog', 'собака'],
  ['dolphin', 'дельфин'],
  ['fish', 'рыба'],
  ['giraffe', 'жираф'],
  ['blouse', 'блузка'],
  ['boot', 'ботинки'],
  ['coat', 'пальто'],
  ['dress', 'платье'],
  ['pants', 'штаны'],
  ['shirt', 'рубашка'],
  ['shoe', 'туфли'],
  ['skirt', 'юбка'],
  ['angry', 'злость'],
  ['happy', 'счастье'],
  ['laugh', 'смех'],
  ['sad', 'грусть'],
  ['scared', 'страх'],
  ['smile', 'улыбка'],
  ['surprised', 'удивление'],
  ['tired', 'усталость'],
  ['dance', 'танцевать'],
  ['dive', 'нырять'],
  ['fly', 'летать'],
  ['walk', 'гулять'],
  ['jump', 'прыгать'],
  ['hug', 'обнимать'],
  ['cry', 'плакать'],
  ['draw', 'рисовать'],
  ['builder', 'строитель'],
  ['doctor', 'врач'],
  ['firefighter', 'пожарник'],
  ['geologist', 'геолог'],
  ['pilot', 'пилот'],
  ['policeman', 'полицейский'],
  ['scientists', 'учёный'],
  ['teacher', 'учитель'],
  ['horse', 'лощадь'],
  ['lion', 'лев'],
  ['mouse', 'мышь'],
  ['pig', 'свинья'],
  ['rabbit', 'кролик'],
  ['sheep', 'овца'],
  ['frog', 'лягушка'],
  ['turtle', 'черепаха'],
  ['fishing', 'рыбачить'],
  ['open', 'открывать'],
  ['play', 'играть'],
  ['point', 'указывать'],
  ['ride', 'ехать'],
  ['run', 'бежать'],
  ['sing', 'петь'],
  ['skip', 'скакать'],
  ['banana', 'банан'],
  ['blackberry', 'ежевика'],
  ['blueberry', 'голубика'],
  ['lime', 'лайм'],
  ['orange', 'апельсин'],
  ['peach', 'персик'],
  ['strawberry', 'клубника'],
  ['watermelon', 'арбуз'],
]);

export enum Mode {
  Play = 'Play',
  Train = 'Train',
}

export enum Cards {
  CardAnimals = 'animals',
  CardClothes = 'clothes',
  CardEmotions = 'emotions',
  CardActions = 'actions',
  CardProffesions = 'proffesions',
  CardAnimals2 = 'animals2',
  CardActions2 = 'actions2',
  CardFruits = 'fruits',
  Main = 'main',
  Stat = 'statistic',
}

export const appRoutes: { [key: string]: string } = {
  '/': 'main',
  '/animals/': 'animals',
  '/clothes/': 'clothes',
  '/emotions/': 'emotions',
  '/actions/': 'actions',
  '/proffesions/': 'proffesions',
  '/animals2/': 'animals2',
  '/actions2/': 'actions2',
  '/fruits/': 'fruits',
  '/statistic/': 'statistic',
};

export enum CategoryNames {
  Animals1 = 'animals',
  Clothes = 'clothes',
  Emotions = 'emotions',
  Actions = 'actions',
  Proffesions = 'proffesions',
  Animals2 = 'animals2',
  Actions2 = 'actions2',
  Fruits = 'fruits',
  Main = 'main',
  Stat = 'statistic',
  Active = 'active',
}

export enum Word {
  Cat = 'cat',
  Bird = 'bird',
  Chick = 'chick',
  Chicken = 'chicken',
  Dog = 'dog',
  Dolphin = 'dolphin',
  Fish = 'fish',
  Giraffe = 'giraffe',
  Blouse = 'blouse',
  Boot = 'boot',
  Coat = 'coat',
  Dress = 'dress',
  Pants = 'pants',
  Shirt = 'shirt',
  Shoe = 'shoe',
  Skirt = 'skirt',
  Happy = 'happy',
  Laugh = 'laugh',
  Sad = 'sad',
  Scared = 'scared',
  Smile = 'smile',
  Surprised = 'surprised',
  Tired = 'tired',
  Dance = 'dance',
  Dive = 'dive',
  Fly = 'fly',
  Walk = 'walk',
  Jump = 'jump',
  Hug = 'hug',
  Cry = 'cry',
  Draw = 'draw',
  Builder = 'builder',
  Doctor = 'doctor',
  Firefighter = 'firefighter',
  Geologist = 'geologist',
  Pilot = 'pilot',
  Policeman = 'policeman',
  Scientists = 'scientists',
  Teacher = 'teacher',
  Horse = 'horse',
  Lion = 'lion',
  Mouse = 'mouse',
  Pig = 'pig',
  Rabbit = 'rabbit',
  Sheep = 'sheep',
  Frog = 'frog',
  Turtle = 'turtle',
  Fishing = 'fishing',
  Open = 'open',
  Play = 'play',
  Point = 'point',
  Ride = 'ride',
  Run = 'run',
  Sing = 'sing',
  Skip = 'skip',
  Banana = 'banana',
  Blackberry = 'blackberry',
  Blueberry = 'blueberry',
  Lime = 'lime',
  Orange = 'orange',
  Peach = 'peach',
  Strawberry = 'strawberry',
  Watermelon = 'watermelon',
}

export enum Translation {
  Cat = 'кот',
  Bird = 'птица',
  Chick = 'цыпленок',
  Chicken = 'курица',
  Dog = 'собака',
  Dolphin = 'дельфин',
  Fish = 'рыба',
  Giraffe = 'жираф',
  Blouse = 'блузка',
  Boot = 'ботинки',
  Coat = 'пальто',
  Dress = 'платье',
  Pants = 'штаны',
  Shirt = 'рубашка',
  Shoe = 'туфли',
  Skirt = 'юбка',
  Happy = 'счастье',
  Laugh = 'смех',
  Sad = 'грусть',
  Scared = 'страх',
  Smile = 'улыбка',
  Surprised = 'удивление',
  Tired = 'усталость',
  Dance = 'танцевать',
  Dive = 'плавать',
  Fly = 'летать',
  Walk = 'гулять',
  Jump = 'прыгать',
  Hug = 'обнимать',
  Cry = 'плакать',
  Draw = 'рисовать',
  Builder = 'строитель',
  Doctor = 'врач',
  Firefighter = 'пожарник',
  Geologist = 'геолог',
  Pilot = 'пилот',
  Policeman = 'полицейкий',
  Scientists = 'ученый',
  Teacher = 'учитель',
  Horse = 'лошадь',
  Lion = 'лев',
  Mouse = 'мышь',
  Pig = 'свинья',
  Rabbit = 'кролик',
  Sheep = 'овца',
  Frog = 'лягушка',
  Turtle = 'черепаха',
  Fishing = 'рыбачить',
  Open = 'открывать',
  Play = 'играть',
  Point = 'указывать',
  Ride = 'ехать',
  Run = 'бежать',
  Sing = 'петь',
  Skip = 'прыгать',
  Banana = 'банан',
  Blackberry = 'ежевика',
  Blueberry = 'голбуика',
  Lime = 'лайм',
  Orange = 'апельсин',
  Peach = 'персик',
  Strawberry = 'клубника',
  Watermelon = 'арбуз',
}

export const imagesPath: CategoryImagesI = {
  animals: 0,
  clothes: 1,
  emotions: 2,
  actions: 3,
  proffesions: 4,
  animals2: 5,
  actions2: 6,
  fruits: 7,
};

export const audioPath: CategoryAudioI = {
  animals: 0,
  clothes: 1,
  emotions: 2,
  actions: 3,
  proffesions: 4,
  animals2: 5,
  actions2: 6,
  fruits: 7,
};
